Add man command
breunigs/frank pull request #39
Opened 2017-04-16 17:51 UTC by Merovius

2017-04-16 22:04 UTC, stapelberg reviewed
Looks good overall.

2017-04-16 22:04 UTC, stapelberg commented on manpages.go
> +var manpagesMatcher = regexp.MustCompile(`\b(\w+)\((\d+)\)(\W|$)`)
Strictly speaking, there are sections which aren’t strictly numerical, e.g. https://manpages.debian.org/jessie/libedit-dev/editline.3edit. A more practical example is 3pl. That said, I expect that in practice, references will usually be restricted to numerical sections. So, maybe add a TODO?

2017-04-16 22:04 UTC, stapelberg commented on manpages.go
> +	msg = strings.TrimPrefix(msg, "frank: ")
I can easily see people writing e.g. “man cherti”. Maybe we should require the “frank: ” prefix?

2017-04-16 23:11 UTC, Merovius commented on manpages.go
> +var manpagesMatcher = regexp.MustCompile(`\b(\w+)\((\d+)\)(\W|$)`)
Is there an example of a section not matching "\d[a-z]+"? I tried to find the most restrictive pattern that still matches everything important to minimize false-positives.

2017-04-16 23:45 UTC, Merovius commented on manpages.go
> +	msg = strings.TrimPrefix(msg, "frank: ")
Grepping through my IRC-logs I indeed find two false positives. Fixed.

2017-04-17 15:08 UTC, stapelberg commented on manpages.go
> +var manpagesMatcher = regexp.MustCompile(`\b(\w+)\((\d+)\)(\W|$)`)
Yes: section names use dashes and underscores. `[0-9][0-9a-z_-]*` matches all current section names, see https://play.golang.org/p/2JytW6o-p_

2017-04-17 16:09 UTC, Merovius commented on manpages.go
> +var manpagesMatcher = regexp.MustCompile(`\b(\w+)\((\d+)\)(\W|$)`)
k fixed

2017-04-17 16:15 UTC, stapelberg approved these changes

2017-04-17 16:16 UTC, stapelberg commented
I’ll leave it up to @cherti to decide whether to do another round of review or merge directly.

2017-04-18 12:27 UTC, cherti requested changes
Only one nitpick regarding the regex, otherwise this looks good to me

2017-04-18 12:27 UTC, cherti commented on manpages.go
> +var manpagesMatcher = regexp.MustCompile(`\b(\w+)\((\d[\da-z_-]*)\)(\W|$)`)
We should add a comment what this shall match, just that later readers of the code don't have to compile the Regex in their head to understand its purpose.

2017-04-18 12:28 UTC, cherti commented on manpages.go
> +var manpagesMatcher = regexp.MustCompile(`\b(\w+)\((\d[\da-z_-]*)\)(\W|$)`)
Doesn't have to be an explicit explanation, just something like "shall match strings like "…" and extract the following parts"

2017-04-24 15:46 UTC, chrko commented on manpages.go
> +var manpagesMatcher = regexp.MustCompile(`\b(\w+)\((\d[\da-z_-]*)\)(\W|$)`)
Hm, I would just point the corresponding tests.

2017-05-01 11:34 UTC, Merovius commented
@cherti PTAL

2017-05-01 11:53 UTC, cherti approved these changes

2017-05-01 11:53 UTC, cherti commented
LGTM, thanks!

2017-05-01 11:54 UTC, merged